### ISSUE TITLE
hsn: add direct family relations

### ISSUE THREAD

**Issue by rijpma** [CLARIAH/wp4-cow-conversions#13]
Relations between persons in the HSN are currently modelled `hsn:person hsndim:individualObservation / hsndim:relToOP hsn:code/relacode`. This means you end up with queries like https://github.com/CLARIAH/wp4-queries-hsn/blob/master/children_in_household_by_mother.rq

Direct relations like `hsn:person ex:childOf hsn:person` should be added. This will not cover all relations in the HSN, but will provide a useful subset of family relations. The documentation should make clear which relations are covered. http://vocab.org/relationship/ could be a good vocab, see http://vos.openlinksw.com/owiki/wiki/VOS/VirtSPARQLReasoningTutorial about how this could be used to infer more family relationships.

**Comment by rlzijdeman** [comment]
Perhaps use the analogy of the ‘RELATE’ variable in NAPP/IPUMS (I think there is a short and long version of RELATE)

On 20 Nov 2019, at 05:59, rijpma <notifications@github.com<mailto:notifications@github.com>> wrote:


Relations between persons in the HSN are currently modelled hsn:person hsndim:individualObservation / hsndim:relToOP hsn:code/relacode. This means you end up with queries like https://github.com/CLARIAH/wp4-queries-hsn/blob/master/children_in_household_by_mother.rq

Direct relations like hsn:person ex:childOf hsn:person should be added. This will not cover all relations in the HSN, but will provide a useful subset of family relations. The documentation should make clear which relations are covered.

**Comment by rijpma** [comment]
closed by bca2d6b7956c552dd38f3fcdf12798977ef4ad77
