### ISSUE TITLE
Opgaafrolle Conversion questions

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/wp4-cow-conversions#7]
Concerning the WIP conversion of the Opgaafrolle:

I read that we are now using dc:creator instead of dc:author, but the example json that was linked in that message is a bit confusing to me; is there an example similar to the one for dc:author?

And now that we're supposed to not use <resource> in our base, do I just adjust the "@base" in the json file appropriately? For example

 `"@base": "https://iisg.amsterdam/resource/", `
 becomes
`  "@base": "https://iisg.amsterdam/", `

Lastly: I changed the AboutURL to `id/{id}` is that correct?

**Comment by Bramvdhout** [comment]
Now concerning the source material:

How should I interpret the columns about horsebreed, cattlebreed, and sheepbreed? They contain numbers that are added to the total of of the respective animal categories, but I'm not sure what they are. It just dawned on me that I probably misinterpreted horseswag as horse wagons.

And, lastly, are the columns about crops sown and reaped (barley, oat, etc) xsd:float types?

**Comment by rlzijdeman** [comment]
Hi @Bramvdhout, I don't think you 'pushed' your file? What's available in git is just the default 'build' metadata-json file.

@Bramvdhout: the changes referred to have perhaps been communicated unclearly, basically it's simple:
- find and replace "dc:author", with "dc:creator"
- find and replace "https://iisg.amsterdam/resource/", with "https://iisg.amsterdam/"
- if there are things you are uncertain about, it's best to be explicit in the rdfs:label. E.g. simple write that you think it's about wagons, if it read's wag. In the review process, we'll see whether 'wag' is 'wagons' or 'wages'. (assuming that the documentation doesn't mention this)
- "xsd:float" for decimals
