### ISSUE TITLE
changed csvw namespace breaks conversions

### ISSUE THREAD

**Issue by rijpma** [CLARIAH/wp4-cow-conversions#8]
@RubenSchalk and myself noticed that commit b6063fde breaks all conversions because it changed the csvw prefix to our custom jsonld csvw context file `http://csvw.clariah-sdh.eculture.labs.vu.nl/csvw.json#`, while it should just be `http://www.w3.org/ns/csvw#"`.

Note that the csvw namespace `http://www.w3.org/ns/csvw#"` has a real role in the conversion process (it is used to query  the metadata graph if I remember correctly), so it should not be changed. I'm also opening an issue in COW that it should somehow not be allowed to be changed.

**Comment by rlzijdeman** [comment]
hi Auke, I'm the one responsible for changing it and I'm sorry for this inconvenience. Nevertheless what I find strange is that (1) I believe the eculture one is the correct reference, (2) at my end nothing broke and actually the cattle service still seems to be working as well.

**Comment by albertmeronyo** [comment]
Hi @rijpma Indeed what @rlzijdeman mentions is the cause of this. We had to change the namespace because that URI is being parsed to further process basic CSVW datatypes

See CLARIAH/COW#22

**Comment by rijpma** [comment]
Sorry about the confusing language on slack, now see that the prefixes are also under `@context`,

What I mean is the distinction between the URL at the top of `@context` rather than the one in the list of prefixes? To be very specific: this should be the eculture one https://github.com/CLARIAH/wp4-cow-conversions/blob/4357755ffea495d09f50396e0700408a421744a4/b2l/siem_long.csv-metadata.json#L53-L54 whereas this one https://github.com/CLARIAH/wp4-cow-conversions/blob/4357755ffea495d09f50396e0700408a421744a4/b2l/siem_long.csv-metadata.json#L97 should not?

For me and @RubenSchalk changing line 97 back to http://www.w3.org/ns/csvw# fixes the conversion failure. What happens at your end?

**Comment by rijpma** [comment]
fixed in a324731d I hope
